name: 'GitHub Actions Weather Bot'

on:
  push:
  schedule:
    - cron: '0 21 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Get Result'
        run: bash ./weather.sh
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.163.com
          server_port: 465
          username: hezijian6338@163.com
          password: hezijian6338
          subject: Shanghai Weather Report
          body: file://result.html
          to: 627222344@qq.com
          from: hezijian6338@163.com
          content_type: text/html
      - name: curl
        uses: wei/curl@v1
        with:
          args: -H Content-Type application/json -X POST https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=76e880f2-6919-4671-aa63-52d05c732400 -d file://result.html
